--[[
	Sheep species stats and spawn chances
]]--

local sheepData = {

	["Basic"] = {
		id = "Basic_Sheep",
		name = "Basic Sheep",
		ShearHealth = 100,
		WoolAmount = 15,
		chance = 80
	},

	["GreySheep"] = {
		id = "Grey_Sheep",
		name = "Grey Sheep",
		ShearHealth = 100,
		WoolAmount = 18,
		chance = 60
	},

	["BrownSheep"] = {
		id = "Brown_Sheep",
		name = "Brown Sheep",
		ShearHealth = 100,
		WoolAmount = 18,
		chance = 60
	},

	["BlackSheep"] = {
		id = "Black_Sheep",
		name = "Black Sheep",
		ShearHealth = 130,
		WoolAmount = 28,
		chance = 30
	},

	["FluffySheep"] = {
		id = "Fluffy_Sheep",
		name = "Fluffy Sheep",
		ShearHealth = 130,
		WoolAmount = 32,
		chance = 30
	},

	["GoldenSheep"] = {
		id = "Golden_Sheep",
		name = "Golden Sheep",
		ShearHealth = 175,
		WoolAmount = 50,
		chance = 12
	},

	["EmeraldSheep"] = {
		id = "Emerald_Sheep",
		name = "Emerald Sheep",
		ShearHealth = 175,
		WoolAmount = 55,
		chance = 12
	},

	["DiamondSheep"] = {
		id = "Diamond_Sheep",
		name = "Diamond Sheep",
		ShearHealth = 250,
		WoolAmount = 100,
		chance = 4
	}

}

return sheepData